main/__init__.py
import os

import jinja2
from flask import Flask

from main.routes import r_base


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile(os.path.join('..', 'config.cfg'))
    template_dir = os.path.join('.', 'templates')
    app.register_blueprint(r_base)
    loader = jinja2.FileSystemLoader(os.path.join('.', template_dir))
    environment = jinja2.Environment(loader=loader)
    if app.app_context():
        return app

main/routes.py
import json
from flask import Blueprint, redirect, render_template

r_base = Blueprint('r_base', __name__, static_folder='static')


@r_base.route('/')
def index():
    vp = 'videos.json'
    with open(vp, encoding='utf-8') as data_file:
        data = json.loads(data_file.read())
    return render_template('views/base/index.html', videos=data)


@r_base.route('/documentacion.zip')
def get_documentation():
    return r_base.send_static_file('grupo2.zip')

main/templates/components/team-member.html
{% macro member(name, email, image, size="col-md-3") %}
<div class="{{ size }} mb-4">
    <div class="card">
        <div class="avatar w-100 white d-flex justify-content-center align-items-center">
            <img src="{{ image }}" class="img-fluid"/>
        </div>
        <div class="card-body">
            <p class="font-weight-bold my-2">{{ name }}</p>
            <p class="text-muted">{{ email }}</p>
        </div>
    </div>
</div>
{% endmacro %}

main/templates/components/timeline.html
{% macro timeline(elements) %}
<div class="row">
    <div class="col-lg-9 mx-auto">
        <ol class="timeline">
            {% for e in elements %}
                <li class="timeline-element">
                    <h5 class="font-weight-bold dark-grey-text mb-3">{{ e.title }}</h5>
                    <p class="grey-text font-small">{{ e.type }}</p>
                    <iframe width="560" height="315" src="{{ e.url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <p class="text-muted">{{ e.description }}</p>
                </li>
            {% endfor %}
        </ol>
    </div>
</div>
{% endmacro %}

main/templates/views/base/documentation.html
<section class="dark-grey-text">
    <div class="row pr-lg-5 mx-5 mb-5">
        <div class="col-md-7 mb-4">

            <div class="view">
                <img src="{{ url_for('.static', filename='img/server.jpg')}}" class="img-fluid w-75 m-auto" alt="smaple image">
            </div>

        </div>
        <div class="col-md-5 d-flex align-items-center">
            <div>

                <h3 class="font-weight-bold mb-4">Documentación</h3>

                <p>En esta sección se encuentran los documentos, pdf, docx y ppt solicitados por el profesor.</p>

                <a href="{{ url_for('r_base.get_documentation')}}" class="btn indigo lighten-2 text-white btn-rounded mx-0">Descargar</a>

            </div>
        </div>
    </div>

</section>

main/templates/views/base/index.html
{% extends 'views/layout/basic.html' %}
{% block content %}
    {% include 'views/base/top.html' %}
    {% include 'views/base/team.html' %}
    {% include 'views/base/documentation.html' %}
    {% include 'views/base/videos.html' %}
{% endblock %}

main/templates/views/base/team.html
{% import 'components/team-member.html' as team %}
<section id="team" class="py-5 teal lighten-4">
    <div class="container">
        <section class="text-center text-lg-left">
            <div class="text-white pb-4">
                <h2 class="text-center font-weight-bold mb-4 pb-1">Integrantes</h2>
                <hr class="w-header mt-4">
            </div>
            <div class="row">
                {{ team.member(
                "Isaac Miranda Madrigal",
                "imirandam@ucenfotec.ac.cr",
                url_for('.static', filename='img/Isaac.jpg')
                ) }}
                {{ team.member(
                "Javier Pozuelo Méndez",
                "jpozuelom@ucenfotec.ac.cr",
                url_for('.static', filename='img/javier.jpg')
                ) }}
                {{ team.member(
                "Matthew Russell Obregón",
                "mrussello@ucenfotec.ac.cr",
                url_for('.static', filename='img/matt.jpg')
                ) }}
                {{ team.member(
                "Sebastián Soto Madrigal",
                "ssotom@ucenfotec.ac.cr",
                url_for('.static', filename='img/me.jpg')
                ) }}
            </div>
        </section>
    </div>
</section>

main/templates/views/base/top.html
{% set img = url_for('.static', filename='img/lego-james-pond.jpg') %}
<section id="top" class="top bg-fp" style="background-image: url('{{ img }}')">
    <h1 class="display-1">Proyecto Final</h1>
</section>

main/templates/views/base/videos.html
{% import 'components/timeline.html' as tml %}
<section id="video" class="py-sm-4 indigo lighten-3">
    <div class="container white z-depth-1 mt-5 py-5 px-4 px-lg-0">
        <section>
            <h3 class="font-weight-bold text-center dark-grey-text pb-2">Vídeos</h3>
            <hr class="w-header mt-4 mb-5">
            <p class="lead text-center text-muted pt-2 mb-5">En esta sección, se muestran los vídeos de instalación y configuración</p>
            {{ tml.timeline(videos) }}
        </section>
    </div>
</section>

main/templates/views/layout/basic.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Grupo 2 Sistemas Operativos</title>
        {#<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">#}
        {#<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">#}
        <link rel="stylesheet" href="{{ url_for('.static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('.static', filename='css/mdb.min.css') }}">
        {% block styles %}{% endblock %}
    </head>

    <body>
        {% include 'views/layout/nav.html' %}
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <footer>
            {% include 'views/layout/footer.html' %}
        </footer>
        <script type="text/javascript" src="{{ url_for('.static', filename='js/jquery.min.js')}}"></script>
        <script type="text/javascript" src="{{ url_for('.static', filename='js/popper.min.js')}}"></script>
        <script type="text/javascript" src="{{ url_for('.static', filename='js/bootstrap.min.js')}}"></script>
        <script type="text/javascript" src="{{ url_for('.static', filename='js/mdb.min.js')}}"></script>
        {% block scripts %}{% endblock %}
    </body>

</html>

main/templates/views/layout/nav.html
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <h1 class="navbar-brand" href="top"><strong>Grupo 2</strong></h1>
    {#<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#g2nav" aria-controls="g2nav" aria-expanded="false" aria-label="Toggle navigation">#}
        {#<span class="navbar-toggler-icon"></span>#}
        {#</button>#}
    {#<div class="collapse navbar-collapse" id="g2nav">#}
        {#<ul class="navbar-nav mr-auto">#}
            {#<li class="nav-item">#}
                {#<a class="nav-link" href="#">Inicio</a>#}
                {#</li>#}
            {#<li class="nav-item">#}
                {#<a class="nav-link" href="#">Integrantes</a>#}
                {#</li>#}
            {#<li class="nav-item">#}
                {#<a class="nav-link" href="#">Documentacion</a>#}
                {#</li>#}
            {#<li class="nav-item">#}
                {#<a class="nav-link" href="#">Videos</a>#}
                {#</li>#}
            {#</ul>#}
        {#</div>#}
</nav>